LinkedInProyect/config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'home'    => 'indices#index'
  get 'about'   => 'static_pages#about'
  get 'crew'    => 'static_pages#crew'
  get 'contact'    => 'static_pages#help'

  get '/user/:id/modify_skills/:skill_id', to: 'users#modify_skills', as:'modify_skills'
  get '/user/:id/skills', to: 'users#skills', as:'my_skills'

  resources :companies
  resources :skills
  resources :users
  resources :indices
  resources :similarities
  resources :about

  post '/indices/index'
  get '/similarities/:company/:id', to: 'similarities#output', as:'get_match'

  get 'confirm_search'    => 'indices#confirm_search'
  get '/accept_crawl/:company/:country/:id', to: 'indices#accept_crawl', as:'accept_crawl'

end

LinkedInProyect/app/models/skill.rb
class Skill
  include Mongoid::Document
  field :name, type: String
  validates_presence_of :name

  before_save :downcase

  has_and_belongs_to_many :users

	#This way is better, with the callback before_save
	def capitalize
		self.name.capitalize!
	end

	#Normalize the value of a string
	def downcase
		self.name.downcase!
	end

end

LinkedInProyect/app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
    @skill = Skill.find(params[:id])
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
    @skill = Skill.find(params[:id])
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to skills_path, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to skills_path, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_path, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:name)
    end
end

LinkedInProyect/app/views/skills/_form.slim
= simple_form_for(@skill) do |f|
  = f.input :name
  = f.button :submit

LinkedInProyect/app/views/skills/edit.slim
h1 Editing skill

= render 'form'

=> link_to 'Show', @skill
=> link_to 'Back', skills_path

LinkedInProyect/app/views/skills/index.slim
h1 Listing skills

table
  tr
    th Name

  - @skills.each do |skill|
    tr
      td = skill.name
      td = link_to 'Show', skill
      td = link_to 'Edit', edit_skill_path(skill)
      td = link_to 'Destroy', skill, 
      method: :delete, data: { confirm: 'Are you sure?' } 

= link_to 'New Skill', new_skill_path

LinkedInProyect/app/views/skills/new.slim
h1 New skill

= render 'form'

=> link_to 'Back', skills_path

LinkedInProyect/app/views/skills/show.slim
h1 Skill Data:

p
	b> Name:
	= @skill.name

p
=> link_to 'Edit', edit_skill_path(@skill)
=> link_to 'Back', skills_path

LinkedInProyect/app/views/skills/simSkills.slim
h1 Listing top-3 skills

table
  tr
    th Name

  - @top3.each do |skill|
  	tr
      td = skill[0].name

LinkedInProyect/app/views/skills/top.slim
h1 Listing top-3 skills