LinkedInProyect/config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'home'    => 'indices#index'
  get 'about'   => 'static_pages#about'
  get 'crew'    => 'static_pages#crew'
  get 'contact'    => 'static_pages#help'

  get '/user/:id/modify_skills/:skill_id', to: 'users#modify_skills', as:'modify_skills'
  get '/user/:id/skills', to: 'users#skills', as:'my_skills'

  resources :companies
  resources :skills
  resources :users
  resources :indices
  resources :similarities
  resources :about

  post '/indices/index'
  get '/similarities/:company/:id', to: 'similarities#output', as:'get_match'

  get 'confirm_search'    => 'indices#confirm_search'
  get '/accept_crawl/:company/:country/:id', to: 'indices#accept_crawl', as:'accept_crawl'

end

LinkedInProyect/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <!--[if lt IE 9]>
	  	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	    </script>
	  <![endif]-->
	</head>
	<body>
		<header class="navbar navbar-default navbar-fixed-top">
			<div class="container">
				<%= link_to "Mining LinkedIn", root_path, id: "logo" %> 
				<nav>
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to "Home", home_path, id: "home" %></li>
						<li><%= link_to "About", about_path, id: "about" %></li>
						<li><%= link_to "Crew", crew_path, id: "crew" %></li>
						<li><%= link_to "Contact", contact_path, id: "help" %></li>
					</ul>
				</nav>
			</div>
		</header>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>