LinkedInProyect/config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'home'    => 'indices#index'
  get 'about'   => 'static_pages#about'
  get 'crew'    => 'static_pages#crew'
  get 'contact'    => 'static_pages#help'

  get '/user/:id/modify_skills/:skill_id', to: 'users#modify_skills', as:'modify_skills'
  get '/user/:id/skills', to: 'users#skills', as:'my_skills'

  resources :companies
  resources :skills
  resources :users
  resources :indices
  resources :similarities
  resources :about

  post '/indices/index'
  get '/similarities/:company/:id', to: 'similarities#output', as:'get_match'

  get 'confirm_search'    => 'indices#confirm_search'
  get '/accept_crawl/:company/:country/:id', to: 'indices#accept_crawl', as:'accept_crawl'

end

LinkedInProyect/app/controllers/indices_controller.rb
class IndicesController < ApplicationController

	def index
		@index = Index.new
 	end

 	#Call the crawler function
 	def create

 		crawler = WebCrawler.new
 		mine_me = MineMe.new
 		company = params[:index][:company].downcase
 		country = params[:index][:country].downcase
 		url = params[:index][:url]

 		unless User.where(:url => url.downcase).exists?
 			the_user = mine_me.mining url
 		end

 		id = User.where(:url => url.downcase).pluck(:_id)[0].to_s

 		company_exists = crawler.search company, country
 		if(company_exists)
 			@company = company
 			@country = country
 			@id = id

 			render :confirm_search #this is the same as "indices"
 		else
			crawler.crawl company, country
			redirect_to get_match_url(company, id)
 		end
 	end

 	def accept_crawl
		company = params[:company]
 		country = params[:country]
 		id = params[:id]
 		crawler = WebCrawler.new
 		crawler.crawl company, country
		redirect_to get_match_url(company, id)
	end

	class MineMe
		require_relative 'MineMe'

		def mining url
			the_user = mine_me_alg(url)

			the_user.each do |key|
					#Create the user if Doesn't exist
					user_name = the_user[0]
					user_url = url

					db_user = User.find_by name: user_name.downcase
					if(!db_user.present?) #create the entity
						db_user = User.new(:name => user_name, :url => user_url)
						db_user.save
					end

					#Create the company if Doesn't exist
					db_company = Company.find_by name: the_user[2][0].downcase
					if(!db_company.present?) #create the entity
						db_company = Company.new(:name => the_user[2][0])
						db_company.save
					end

					#Create the skills if Doesn't exist, and add the skills to the user
					my_skills = db_user.skills
					the_user[1].each do |skill|
						db_skill = Skill.find_by name: skill.downcase
						if(!db_skill.present?) #create the entity
							db_skill = Skill.new(:name => skill)
							db_skill.save
						end

						unless my_skills.include? db_skill
					      db_user.skills << db_skill
					      db_user.save
					    end
					end

					#Add the company to the user
					db_user.company = db_company
				    db_user.save
				end
		end
	end

 	class WebCrawler
 		#Gems that are required
		require 'rubygems'
		require 'mechanize'
		require 'nokogiri'
		require 'open-uri'
		require 'json'

		#Other ruby files that are required
		#require_relative 'NameSkills'
		#require_relative 'AlsoViewed'
		require_relative 'webcrawler'
		require_relative 'AlsoViewed'

 		def search company, country
 			#This is to debug the app, it's displayed on the console

	 		#Initialize Mechanize
			agent = Mechanize.new
			#These rows may be unnecessary, remove if it proves problems for Windows/Linux
			agent.user_agent_alias = "Mac Safari"
			agent.follow_meta_refresh = true

			#Check if the company is already in the DB
			db_company = Company.find_by name: company.downcase
			p db_company
			if(db_company.present?)
				return true
			end

		end

		def crawl company, country

			p "VOY A CORRER EL WEBCRAWLER!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

			poi_tot, total_time1, total_time2 = webcrawlerfunc(company, country)
			puts "Adding your data to the MongoLab database. I can see the finish line now!"
			beginning_time = Time.now

			#Add data to the database.
			poi_tot.keys.each do |key|
				#Create the user if Doesn't exist
				user_name = poi_tot[key]["Name"]
				user_url = poi_tot[key]["LinkedIn URL"]

				db_user = User.find_by name: user_name.downcase
				if(!db_user.present?) #create the entity
					db_user = User.new(:name => user_name, :url => user_url)
					db_user.save
				end

				#Create the company if Doesn't exist
				db_company = Company.find_by name: company.downcase
				if(!db_company.present?) #create the entity
					db_company = Company.new(:name => company)
					db_company.save
				end

				#Create the skills if Doesn't exist, and add the skills to the user
				my_skills = db_user.skills
				poi_tot[key]["Skills"].each do |skill|
					db_skill = Skill.find_by name: skill.downcase
					if(!db_skill.present?) #create the entity
						db_skill = Skill.new(:name => skill)
						db_skill.save
					end

					unless my_skills.include? db_skill
				      db_user.skills << db_skill
				      db_user.save
				    end
				end

				#Add the company to the user
				db_user.company = db_company
			    db_user.save
			end


			end_time = Time.now
			total_time3 = end_time - beginning_time
			total_time = total_time1 + total_time2 + total_time3
			puts "Added to your database in #{total_time3} seconds."
			puts
			puts "Finished the job in #{total_time} seconds. Go have a look at your results!"

 		end
 	end
end

LinkedInProyect/app/views/indices/_form.slim
= simple_form_for(@index) do |f|

  | We need the url to your public LinkedIn-profile:
  = f.input :url, placeholder:"   LinkedIn URL goes here.", label:false

  | What company are you interested in?
  = f.input :company, placeholder:"  Company name goes here.", label:false

  | Where do most of the company employees reside?
  = f.input :country, label:false

  = f.button :submit, "Submit", data: { confirm: "Please notice that this process could take up to 5 minutes. Go grab a cup of coffee and hold on tight!"}

LinkedInProyect/app/views/indices/confirm_search.slim
<div class="jumbotron">
	h4 It seems the company you are searching for is already in the database. Do you still want to search for more data?
	<div class="row">
	 	<div class="col-xs-6 col-md-3 col-md-offset-2">
	 		- if @country.present?
				= link_to 'Yes, repeat the search!', accept_crawl_path(@company, @country, @id), class:"yeslink", data: { confirm: "Please notice that this process could take up to 5 minutes. Go grab a cup of coffee and hold on tight!"}
			- else
				= link_to 'Yes, repeat the search!', accept_crawl_path(@company, "com", @id), class:"yeslink", data: { confirm: "Please notice that this process could take up to 5 minutes. Go grab a cup of coffee and hold on tight!"}

	 	</div>
	  	<div class="col-xs-6 col-md-3 col-md-offset-2">
	  		= link_to 'No, continue with the stored data.', get_match_path(@company, @id), class:"nolink"
	  	</div>
	</div>
</div>

LinkedInProyect/app/views/indices/index.slim
= provide(:title, "Home")

<body class="home">
	<div class="center jumbotron", id:"homepage">
		h1 Let's get you started by filling out this form.
		<div id:"indexform">
			= render 'form'
		</div>
	</div>
</body>

LinkedInProyect/app/views/indices/indices.slim
h1 operation successfully completed