LinkedInProyect/config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'home'    => 'indices#index'
  get 'about'   => 'static_pages#about'
  get 'crew'    => 'static_pages#crew'
  get 'contact'    => 'static_pages#help'

  get '/user/:id/modify_skills/:skill_id', to: 'users#modify_skills', as:'modify_skills'
  get '/user/:id/skills', to: 'users#skills', as:'my_skills'

  resources :companies
  resources :skills
  resources :users
  resources :indices
  resources :similarities
  resources :about

  post '/indices/index'
  get '/similarities/:company/:id', to: 'similarities#output', as:'get_match'

  get 'confirm_search'    => 'indices#confirm_search'
  get '/accept_crawl/:company/:country/:id', to: 'indices#accept_crawl', as:'accept_crawl'

end

LinkedInProyect/app/models/user.rb
class User
  include Mongoid::Document
  field :name, type: String
  field :url, type: String
  validates_presence_of :name, :url

  before_save :downcase

  belongs_to :company
  has_and_belongs_to_many :skills

  scope :users_by_name, -> { order(name: :asc) }

#Capitalize the users names
#This way is incorect, because iterates over all the users
#It's better doing the capitalization when a user is created or shown
  #def self.capitalize_all  
  #  User.each do |u|
  #    u.name = u.name.downcase
  #    u.save
  #  end
  #end

#logger.debug "---------------------MY_LOG------------------------"
#logger.debug @user.name

#This way is better, with the callback before_save
  def capitalize
      self.name.capitalize!
  end

#Normalize the value of a string
  def downcase
	  self.name.downcase!
    self.url.downcase!
  end

end

LinkedInProyect/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:skills, :modify_skills, :show, :edit, :update, :destroy]
  before_action :set_skills, only: [:skills, :modify_skills]

  # GET /users
  # GET /users.json
  def index
    @users = User.users_by_name
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #Add or Delete a skill
  def modify_skills
    @my_skills = @user.skills
    skill = Skill.find(params[:skill_id])

    unless @my_skills.include? skill
      @user.skills << skill
    else
      @user.skills.delete(skill)
    end

    @user.save

    render 'skills'
  end


  #Show all skills
  def skills
    @my_skills = @user.skills
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :url, :company)
    end

    # To get all the movies of the database
    def set_skills
      @skills = Skill.all
    end
end

LinkedInProyect/app/views/users/_form.slim
= simple_form_for(@user) do |f|
  = f.input :name
  = f.input :url
  = f.input :company, :collection => Company.all, as: :select
  = f.button :submit

LinkedInProyect/app/views/users/edit.slim
h1 Editing user

= render 'form'

=> link_to 'Show', @user
=> link_to 'Back', users_path

LinkedInProyect/app/views/users/index.slim
h1 Listing users

table
  tr
    th Name
    th Url
    th Company

  - @users.each do |user|
    tr
      td = user.name.titleize
      td = user.url
      - if user.company
        td = user.company.name
      - else
        td
      td = link_to 'Show', user
      td = link_to 'Edit', edit_user_path(user)
      td = link_to 'Delete', user, :confirm => 'Are you sure?', :method => :delete
      td = link_to 'Show/Edit skills', my_skills_path(user)

=> link_to 'New User', new_user_path

LinkedInProyect/app/views/users/new.slim
h1 New user

= render 'form'

= link_to 'Back', users_path

LinkedInProyect/app/views/users/show.slim
h1 User Data:

p
	b> Name:
	= @user.name
p
	b> Url:
	= @user.url

p
	b> Company:
	- if @user.company
          = @user.company.name
	
p
=> link_to 'Edit', edit_user_path(@user)
=> link_to 'Back', users_path

LinkedInProyect/app/views/users/skills.slim
h1 = @user.name.titleize

table
  tr
    th Skills

  - @skills.each do |skill|
    tr
      td 
        - if @my_skills.include? skill
          = link_to '[ * ]', modify_skills_path(@user, skill)
        - else
          = link_to '[ _ ]', modify_skills_path(@user, skill)

        = skill.name

= link_to 'Back', users_path